#!/usr/bin/env ruby

require 'rubygems'
require 'trollop'
require 'cmdb'

if gemspec = Gem.loaded_specs['cmdb']
  gemspec_version = gemspec.version
else
  require_relative '../lib/cmdb/version'
  gemspec_version = CMDB::VERSION
end

commands = {}
CMDB::Commands.constants.each do |konst|
  name = konst.to_s.downcase
  commands[name] = CMDB::Commands.const_get(konst.to_sym)
end

# Use a Trollop parser for help/banner display, but do not actually parse
# anything just yet.
command_list = commands.keys - ['help']
command_info = command_list.map { |c| "       * #{c}" }.join("\n")
p = Trollop::Parser.new do
  version "cmdb #{gemspec_version} (c) 2013-2014 RightScale, Inc."
  banner <<-EOS
A command-line interface for configuration management.

Usage:
       cmdb <command> [options]

Where <command> is one of:
#{command_info}

To get help on a command:
       cmdb help command
  EOS

  stop_on commands.keys
end

opts = Trollop::with_standard_exception_handling p do
  raise Trollop::HelpNeeded if ARGV.empty?
  p.parse ARGV
  cmd = ARGV.shift
  klass = commands[cmd]

  if klass
    klass.create.run
  else
    raise ArgumentError, "Unrecognized command #{cmd}"
  end
end
